export default function About() {
  return (
    <div className="pt-32 px-8 md:px-24 pb-24 max-w-4xl mx-auto min-h-screen">
      <h1 className="text-sm text-brand-moss uppercase tracking-[0.2em] mb-12">Methodology</h1>
      <h2 className="text-5xl md:text-6xl font-light mb-16 text-brand-ink">Environmental Intelligence</h2>
      
      <div className="space-y-12 text-lg leading-relaxed text-brand-ink/80 font-light">
        <section>
          <h3 className="text-xl font-medium text-brand-ink mb-6">What AeroTrace Does</h3>
          <p>
            AeroTrace is a platform designed to trace anomalous pollution events to their most probable industrial sources. By combining high-frequency sensor networks with real-time meteorological data, we reconstruct the atmospheric trajectory of a pollutant backwards from the point of detection.
          </p>
        </section>

        <section>
          <h3 className="text-xl font-medium text-brand-ink mb-6">Observation & Detection</h3>
          <p>
            The system continuously monitors a network of environmental sensors. When a significant concentration spike is detected above the established baseline, an anomalous event is generated.
          </p>
        </section>

        <section>
          <h3 className="text-xl font-medium text-brand-ink mb-6">Trajectory Reconstruction</h3>
          <p>
            Using wind direction and speed data at the exact time of the event, we calculate the reverse trajectory. This determines the spatial origin of the air mass prior to reaching the sensor.
          </p>
        </section>

        <section>
          <h3 className="text-xl font-medium text-brand-ink mb-6">Attribution & Uncertainty</h3>
          <div className="p-6 bg-brand-soft/30 border-l-2 border-brand-moss text-brand-ink mb-4">
            AeroTrace provides <strong>evidence-based attribution analysis</strong>. It does NOT establish legal responsibility or definitive causation.
          </div>
          <p>
            Candidates are isolated based on wind alignment, estimated travel time, spatial distance, and matching emission signatures. However, environmental modeling inherently contains uncertainty. Reports generated by this system are designed to inform deeper investigations, not to serve as absolute conclusions.
          </p>
        </section>
      </div>
    </div>
  );
}
