import { FileText, Download } from 'lucide-react';

export default function Reports() {
  const dummyReports = [
    { id: 'REP-2026-10-08-01', title: 'Source Attribution Analysis', event: 'EVT-001', date: '2026-10-08T14:30:00Z', status: 'Finalized' },
    { id: 'REP-2026-10-07-04', title: 'Meteorological Baseline', event: 'N/A', date: '2026-10-07T09:00:00Z', status: 'Auto-Generated' },
    { id: 'REP-2026-10-05-02', title: 'Source Attribution Analysis', event: 'EVT-042', date: '2026-10-05T16:45:00Z', status: 'Pending Review' },
  ];

  return (
    <div className="pt-32 px-8 md:px-24 pb-24 max-w-7xl mx-auto min-h-screen">
      <h1 className="text-sm text-brand-moss uppercase tracking-[0.2em] mb-12">Evidence Archive</h1>
      <h2 className="text-5xl md:text-6xl font-light mb-16 text-brand-ink">Investigation Reports</h2>
      
      <div className="bg-brand-soft/20 border border-brand-soft rounded-2xl p-8 mb-16">
        <p className="text-brand-ink/70 max-w-2xl leading-relaxed">
          Official PDF reports generated by the AeroTrace backend engine. These reports contain forensic analysis, timeline reconstructions, and evidence mapping suitable for compliance review.
        </p>
      </div>

      <div className="flex flex-col gap-4">
        <div className="grid grid-cols-12 gap-4 text-xs font-mono text-brand-moss uppercase tracking-widest border-b border-brand-soft pb-4 mb-4 px-4">
          <div className="col-span-3">Report ID</div>
          <div className="col-span-4">Type</div>
          <div className="col-span-2">Event</div>
          <div className="col-span-2">Date</div>
          <div className="col-span-1 text-right">Action</div>
        </div>

        {dummyReports.map(report => (
          <div key={report.id} className="grid grid-cols-12 gap-4 text-sm text-left py-6 px-4 bg-white border border-brand-soft hover:border-brand-moss transition-all items-center rounded-lg shadow-sm">
            <div className="col-span-3 font-mono text-brand-ink">{report.id}</div>
            <div className="col-span-4 flex items-center gap-3">
              <FileText size={16} className="text-brand-moss" />
              <span className="font-medium">{report.title}</span>
            </div>
            <div className="col-span-2 text-brand-ink/70">{report.event}</div>
            <div className="col-span-2 font-mono text-brand-ink/60">{new Date(report.date).toLocaleDateString()}</div>
            <div className="col-span-1 flex justify-end">
              <button className="p-2 text-brand-moss hover:bg-brand-soft rounded transition-colors" title="Download Report">
                <Download size={18} />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
